# Generated by Django 4.2.28 on 2026-02-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order_index', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
